/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UX9k2p7q4n8RouteImport } from './routes/u-x9k2p7q4n8'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UX9k2p7q4n8Route = UX9k2p7q4n8RouteImport.update({
  id: '/u-x9k2p7q4n8',
  path: '/u-x9k2p7q4n8',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/u-x9k2p7q4n8': typeof UX9k2p7q4n8Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/u-x9k2p7q4n8': typeof UX9k2p7q4n8Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/u-x9k2p7q4n8': typeof UX9k2p7q4n8Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/u-x9k2p7q4n8'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/u-x9k2p7q4n8'
  id: '__root__' | '/' | '/about' | '/u-x9k2p7q4n8'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UX9k2p7q4n8Route: typeof UX9k2p7q4n8Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/u-x9k2p7q4n8': {
      id: '/u-x9k2p7q4n8'
      path: '/u-x9k2p7q4n8'
      fullPath: '/u-x9k2p7q4n8'
      preLoaderRoute: typeof UX9k2p7q4n8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UX9k2p7q4n8Route: UX9k2p7q4n8Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
